### ISSUE TITLE
Regex

### ISSUE THREAD

**Issue by denis-n** [mxmCherry/godd#1]
Hi,

I was thinking of porting device detection library from PHP to Golang, but Go is not supporting PHP's regex :(

So have you tried this package for PCRE? Does it work?

https://github.com/glenn-brown/golang-pkg-pcre

Dennis

**Comment by mxmCherry** [comment]
Hello.

I wanted pure Go PCRE implementation, but there were only bindings and I try to avoid using them. Mentioned one seems to be quite old as well.

That's why I did [this hack](https://godoc.org/github.com/mxmCherry/godd#RawDeviceMobileRuleSet.Hack_WithoutUnsupportedPCRE).

If you really need the same behavior as piwik, you'd better fork this repo to use with PCRE bindings.

P.S.: I'm not using this project actively. As I remember, piwik got major version bump, so this lib may not work with it's latest regexps (if they still use regexps).
